#!/bin/bash -e
basename=`basename $0`
dirname=`dirname $0`
dirname=`cd "$dirname" && pwd`

# FIXME: change directories; as the maven-launcher can get confused if another .mvn/ is found
cd ${dirname}

exec ${dirname}/.maven-launcher \
  -e \
  -f ${dirname}/config.xml \
  com.planet57.gshell:gshell-maven-plugin:run \
  -Dgshell.arguments="$@"
